<MainView>
  GridLayout:
    cols:1
    size:root.width, root.height

    Image:
      source: "Views/Images/diario.png"

    GridLayout:
      cols:2

      Button:
        text: "Login"

      Button:
        text: "Registrar"


<RegisterView>
  GridLayout:
    cols:1
    size:root.width, root.height

    GridLayout:
      cols:2

      Label:
        text:"Nome"

      TextInput:
        multiline:False

